version: '3'

services:
  sqlserver:
    container_name: sqlserver-db
    hostname: mssql-db
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    user: root
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'yourStrong(!)PasswordDD' # User SA
    ports:
      - "1433:1433"
    volumes:
      - sqlserver:/var/opt/mssql
      
  postgres:
    container_name: qso
    image: 17.0-alpine
    environment:
      POSTGRES_DB: 'qso_example'
      POSTGRES_USER: 'qso_user'
      POSTGRES_PASSWORD: 'qso_password'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - app-network
    external_links:
      - app-network
    volumes:
      - ./.docker-volumes/pgdata2:/var/lib/postgresql/data

  mongodb_container:
    image: mongo:8.0.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  redis:
    container_name: qso_redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - .:/usr/app
    networks:
      - app-network
  # app:
  #   build:
  #     context: .
  #   container_name: app-all-module
  #   command: yarn start:dev
  #   ports:
  #     - '3002:3002'
  #   volumes:
  #     - .:/usr/app
  #   networks:
  #     - app-network
  #   depends_on:
  #     - postgres
  #     - mongodb_container
  #     - redis
  #   volumes:
  #    - .:/app

  # app-credit:
  #   build:
  #     context: .
  #   container_name: app-credit
  #   command: yarn credit:start:dev
  #   ports:
  #     - '3003:3003'
  #   volumes:
  #     - .:/usr/app
  #   networks:
  #     - app-network

networks:
  app-network:

volumes:
  mongodb_data_container:
